export const TalentProfile = [
  {
    id: 0,
    picture: "../static/Ellipse 607.png",
    name: "Rolak Ogbonna",
    company: "Figma",
    location: "Albany, NY",
    title: "Product designer",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lorem euismod nulla sit turpis libero. Ac rhoncus nibh senectus adipiscing. Aliquet habitant .",
    views: "10",
    applicants: "2",
    pay: "$32k - $60k",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    full_description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    skills: [
      "Proven UI/UX Experience: Minimum 3 years of experience designing customer-facing products on web and mobile devices.",
      "User-Centric Design: Strong background in developing wireframes and prototypes, with a keen understanding of when and how to apply different design methodologies.",
      " Research and Testing: Experience in conducting user research and usability testing to validate designs and improve user satisfaction.",
      " Technical Proficiency: Advanced skills in Figma, Adobe XD, or similar design tools.",
      " Collaboration Skills: Proven ability to collaborate effectively with cross-functional teams, including product managers and engineers.",
      " Educational Background: A degree in Design, Interaction Design, Visual Communications, or a related field is preferred.",
    ],
    fulltime: true,
    onsite: true,
    employees: "100-200",
    deadline: "March 6, 2018",
  },
  {
    id: 2,
    picture: "/my-vite-app/src/assets/images/Ellipse 607.png",
    name: "Rolak Ogbonna",
    company: "Figma",
    location: "Albany, NY",
    title: "Product designer",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lorem euismod nulla sit turpis libero. Ac rhoncus nibh senectus adipiscing. Aliquet habitant .",
    views: "10",
    applicants: "2",
    pay: "$32k - $60k",
  },
  {
    id: 1,
    picture: "/my-vite-app/src/assets/images/Ellipse 607.png",
    company: "Figma",
    name: "Rolak Ogbonna",
    location: "Albany, NY",
    title: "Product designer",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lorem euismod nulla sit turpis libero. Ac rhoncus nibh senectus adipiscing. Aliquet habitant .",
    views: "10",
    applicants: "2",
    pay: "$32k - $60k",
  },
  {
    id: 4,
    picture: "/my-vite-app/src/assets/images/Ellipse 607.png",
    name: "Rolak Ogbonna",
    company: "Figma",
    location: "Albany, NY",
    title: "Product designer",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lorem euismod nulla sit turpis libero. Ac rhoncus nibh senectus adipiscing. Aliquet habitant .",
    views: "10",
    applicants: "2",
    pay: "$32k - $60k",
  },
  {
    id: 5,
    picture: "/my-vite-app/src/assets/images/Ellipse 607.png",
    name: "Rolak Ogbonna",
    company: "Figma",
    location: "Albany, NY",
    title: "Product designer",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lorem euismod nulla sit turpis libero. Ac rhoncus nibh senectus adipiscing. Aliquet habitant .",
    views: "10",
    applicants: "2",
    pay: "$32k - $60k",
  },
  {
    id: 6,
    picture: "/my-vite-app/src/assets/images/Ellipse 607.png",
    name: "Rolak Ogbonna",
    company: "Figma",
    location: "Albany, NY",
    title: "Product designer",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lorem euismod nulla sit turpis libero. Ac rhoncus nibh senectus adipiscing. Aliquet habitant .",
    views: "10",
    applicants: "2",
    pay: "$32k - $60k",
  },
  {
    id: 7,
    picture: "/my-vite-app/src/assets/images/Ellipse 607.png",
    name: "Rolak Ogbonna",
    company: "Figma",
    location: "Albany, NY",
    title: "Product designer",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lorem euismod nulla sit turpis libero. Ac rhoncus nibh senectus adipiscing. Aliquet habitant .",
    views: "10",
    applicants: "2",
    pay: "$32k - $60k",
  },
  {
    id: 8,
    picture: "/my-vite-app/src/assets/images/Ellipse 607.png",
    name: "Rolak Ogbonna",
    company: "Figma",
    location: "Albany, NY",
    title: "Product designer",
    description:
      "Lorem ipsum dolor sit amet consectetur. Lorem euismod nulla sit turpis libero. Ac rhoncus nibh senectus adipiscing. Aliquet habitant .",
    views: "10",
    applicants: "2",
    pay: "$32k - $60k",
  },
  //   {
  //     id: 9,
  //     picture: "/src/static/images/John.png",
  //     name: "Rolak Ogbonna",
  //     company: "Figma",
  //     location: "Albany, NY",
  //     title: "Product designer",
  //     description:
  //       "Lorem ipsum dolor sit amet consectetur. Lorem euismod nulla sit turpis libero. Ac rhoncus nibh senectus adipiscing. Aliquet habitant .",
  //     views: "10",
  //     applicants: "2",
  //     pay: "$32k - $60k",
  //   },
  //   {
  //     id: 10,
  //     picture: "/src/static/images/John.png",
  //     name: "Rolak Ogbonna",
  //     company: "Figma",
  //     location: "Albany, NY",
  //     title: "Product designer",
  //     description:
  //       "Lorem ipsum dolor sit amet consectetur. Lorem euismod nulla sit turpis libero. Ac rhoncus nibh senectus adipiscing. Aliquet habitant .",
  //     views: "10",
  //     applicants: "2",
  //     pay: "$32k - $60k",
  //   },
];
